---
title: "Mid-quarter essay prompt"
subtitle: "EDUC 250B, Winter 2021"
author: 
date: 
urlcolor: blue
output: 
  # pdf_document
  # word_document:
  #   toc: no
  #   toc_depth: '3'
  html_document:
    toc: true
    toc_depth: 3
    toc_float: true
    number_sections: true
    fig_caption: true
    highlight: tango
    theme: default
    df_print: tibble
bibliography: ../lectures/educ250_bib.bib
csl: ../lectures/apa.csl
---

# Essay prompt

<!-- your comment 
The "Combahee River Collective" published the 1977 _Combahee River Collective Statement_, which became an important document in the development of Black feminism. 

-->

The "Combahee River Collective" was a Black feminist organization best known for publishing the 1977 _Combahee River Collective Statement_, which became an important document in the development of Black feminism @RN4570. @RN869 develop an old institutionalism analysis of the origins institutionalization of the "terminal vocational education" mission of the community college. Your task is, first, to develop an old institutionalism analysis of the origins and institutionalization of the _Combahee River Collective Statement_. How do the limitations of old institutionalism as a theoretical perspective undermine this analysis? How can selected ideas/concepts from Black feminism be incorporated to develop a more insightful analysis about the origins of the  _Combahee River Collective Statement_ and/or explanation for why this statement has been so impactful?


# General guidelines/recommendations

- Essay assigned 1/27/2021 [week 4 synchronous class] and is due before class on 2/10/2021 [week 6 synchronous class]
- Essay is worth 10% of your grade for the quarter
- Submit essay [here](https://www.dropbox.com/request/Ea4MWcYgHdbXUtrwDBYd)
- Essay should be three to four pages (excluding references) double space, size 11 or 12 font, one inch margins all around
  - A bit less than three pages is fine, but cannot be longer than four pages
- On old institutionalism
  - In addition to lecture slides and assigned readings, this handout on old institutionalism may be useful: [LINK](https://anyone-can-cook.github.io/orgs_class/lectures/old_institutionalism2/old_institutionalism_overview.html)
  - Note that there are different “flavors” of old institutionalism. These different flavors share some common ideas/approaches that are fundamental to old institutionalism, but differ in other ways (For example, Selznick focuses on extent to which the "operative system" supports organizational values and how changes in operative system strengthen/weaken "institutional guardians" that protect organizational values).  You can be selective about which “flavor” of old institutionalism you draw from (but choose the flavor that you think is best for this analysis). Also, given space limitations, you can be selective about which concepts you introduce.
  - Try to take old institutionalism as far as it can go in analyzing the Combahee River Collective, as opposed to creating a "paper tiger" analysis.
- Follow APA style
  - Use citations when appropriate
  -	Any verbatim text from another source MUST be cited and quoted; failure to do this will be considered plagiarism and will result in no credit for the assignment
- We are very happy to make an appointment with you to discuss your essay
  - Prior to the meeting, please prepare an outline of your essay. This will make our conversation more productive

# Writing expectations/recommendations

- Create an outline to develop logical flow of ideas/argument
- Aim for clear, simple prose that is easy for reader to follow
- Each paragraph should be about one idea/topic (could be big or small)
- First sentence [“topic sentence”] of paragraph tells reader what paragraph is
about
- Subsequent sentences flesh out the idea of topic sentence, develop logical
argument and/or empirical evidence

